import type { NextPage } from 'next';
import Head from 'next/head';
import Banner from '../components/Banner';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>BitSenpai</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/static/images/logo.svg' />
            </Head>
            <Banner />
        </>
    );
};

export default Home;
